# Generated by Django 5.2.5 on 2025-08-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
